# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 

configfile: "config/config.yaml"

report: "report/workflow.rst"

container: "docker://continuumio/miniconda3"

include: "rules/common.smk"
include: "rules/prep_files.smk"
include: "rules/gffread.smk"
include: "rules/samtools.smk"
include: "rules/bwa.smk"
include: "rules/bowtie2.smk"
include: "rules/salmon.smk"
include: "rules/star.smk"

rule all:
    input: final_outputs # defined in common.smk