# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 

localrules: all, download, uncompress

configfile: "config/options.yaml"

report: "report/workflow.rst"

# singularity: "docker://continuumio/miniconda3"
singularity: "docker://condaforge/mambaforge"

include: "rules/common.smk"
include: "rules/download.smk"
include: "rules/samtools.smk"
include: "rules/gffread.smk"
include: "rules/bwa.smk"
include: "rules/bowtie2.smk"
include: "rules/star.smk"
include: "rules/salmon.smk"
include: "rules/hisat2.smk"
include: "rules/uncompress.smk"

rule all:
    input: final_outputs # defined in common.smk