# see https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html

# CSD3 default resources (comment/uncomment as preferred)
default-resources:
    slurm_account: a-downie-sl3-cpu
    # slurm_partition: icelake
    # mem_mb_per_cpu: 3370
    slurm_partition: sapphire
    mem_mb_per_cpu: 4580

# container settings
use-singularity: True
use-conda: True

# SLURM execution
executor: slurm
jobs: 100                        # restrict number of submitted jobs to 100
max-jobs-per-second: 1           # don't abuse SLURM
max-status-checks-per-second: 1  # don't abuse SLURM
keep-going: True                 # if a job fails, continue the pipeline for other jobs
rerun-incomplete: True
printshellcmds: True             # print shell commands that are run
latency-wait: 20

# resources for each rule
set-resources:
    samtools_index:
        runtime: 360
        cpus_per_task: 24
    gffread:
        runtime: 360
        cpus_per_task: 24
    bwa_index:
        runtime: 360
        cpus_per_task: 24
    bowtie2_build:
        runtime: 360
        cpus_per_task: 24
    star_index:
        runtime: 360
        cpus_per_task: 48
    salmon_decoy:
        runtime: 360
        cpus_per_task: 4
    salmon_index:
        runtime: 360
        cpus_per_task: 24
    hisat2_index:
        runtime: 360
        cpus_per_task: 24
    bwa_mem2_index:
        runtime: 360
        cpus_per_task: 24
    bwa_meme_index:
        runtime: 360
        cpus_per_task: 24